name: unit-test-alt

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: semver
        id: semver
        uses: ./
        with:
          value: |
            1.2.3
            3.4.5
            5.6.7
          pattern: "{major}.{minor}"
    outputs:
      version: ${{ steps.semver.outputs.version }}

  build:
    runs-on: ubuntu-latest
    needs: generate
    strategy:
      matrix:
        version: ${{ fromJson(needs.generate.outputs.version) }}
    steps:
      - run: echo "Build ${{ matrix.version }}"
